### ISSUE TITLE
Create a Docker Compose-based production deployment example

### ISSUE THREAD

**Issue by lunkwill42** [Uninett/argus-docker#1]
For ease of deployment and review of Argus as a complete system, we should have a Docker Compose-definition that is more production-oriented.

This should likely also contain a pipeline that builds and publishes Docker containers on the Dockerhub for the frontend and backend components, so that these could potentially be re-used in K8s deployments as well.

**Comment by lunkwill42** [comment]
@hmpf Can you have a look?

**Comment by hmpf** [comment]
```
% docker compose up
docker: 'compose' is not a docker command.
```

**Comment by lunkwill42** [comment]
> On a freshly installed debianish system:
> 
> ```
> $ docker compose up
> docker: 'compose' is not a docker command.
> ```

"debian-ish" might be key here. `docker-compose` used to be a separate binary from Docker, but has lately been implemented as a subcommand to `docker` itself. If I follow the Docker installation instructions on the current Debian stable distro, I get a `docker` command has the `compose` subcommand, rather than the `docker-compose` binary.

This was also a source of confusion when re-establishing the CNaaS lab recently, since the old one ran on an older Debian distro.

I tend to alias `dc` to either `docker compose` or `docker-compose`, depending on the system (I never use the system `dc` binary, and I hate typing long command names over and over). Maybe this could be a tip in the README?



> ```
> $ docker-compose up
> Traceback (most recent call last):
>   ..
>   File "/usr/lib/python3/dist-packages/docker/transport/unixconn.py", line 30, in connect
>     sock.connect(self.unix_socket)
> PermissionError: [Errno 13] Permission denied
> ```
> 
> ```
> $ sudo usermod -a -G docker hmpf
> ```

This is more or less bog standard copy&paste installatioan instructions for
Docker installations on Linux. I'm not sure we should bother to quote the
Docker installation instructions for every platform in our README?


> I notice that it drags in argus-server 1.9.0. It'd be better if it used 1.10.2.

Indeed, but 1.9.0 was the latest release when I first made this repo. Fortunately, every new release automatically builds a new Docker image now, so changing this is pretty simple.

> Also, it defaults to running argus-server on port 8000. You should document how to run it on some other port, ditto postgresql, since I had to turn existing stuff off to get it to run.

You had to turn off other PostgreSQL servers or other web services? Only the argus frontend/backend web servers need to be exposed on the localhost to be able to use them - The PostgreSQL and Redis services are only made available in the compose environment's internal network.

> After getting past point 1 it crashes out with a gloriously long traceback again, this is as far as I've gotten.

What can I say? It all works for me? :-D Can you post said gloriously long traceback?

**Comment by lunkwill42** [comment]
> What can I say? It all works for me? :-D Can you post said gloriously long traceback?

Funnily enough, @hmpf, v1.9.0 works for me, but if I try to upgrade to v1.10.2, the backend crashes:

```
argus-docker-api-1       | Post-processing 'rest_framework/css/bootstrap.min.css' failed!
argus-docker-api-1       |
argus-docker-api-1       | Traceback (most recent call last):
argus-docker-api-1       |   File "/usr/local/bin/django-admin", line 8, in <module>
argus-docker-api-1       |     sys.exit(execute_from_command_line())
argus-docker-api-1       |   File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
argus-docker-api-1       |     utility.execute()
argus-docker-api-1       |   File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 440, in execute
argus-docker-api-1       |     self.fetch_command(subcommand).run_from_argv(self.argv)
argus-docker-api-1       |   File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 402, in run_from_argv
argus-docker-api-1       |     self.execute(*args, **cmd_options)
argus-docker-api-1       |   File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 448, in execute
argus-docker-api-1       |     output = self.handle(*args, **options)
argus-docker-api-1       |   File "/usr/local/lib/python3.9/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 209, in handle
argus-docker-api-1       |     collected = self.collect()
argus-docker-api-1       |   File "/usr/local/lib/python3.9/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 154, in collect
argus-docker-api-1       |     raise processed
argus-docker-api-1       | whitenoise.storage.MissingFileError: The file 'rest_framework/css/bootstrap.min.css.map' could not be found with <whitenoise.storage.CompressedManifestStaticFilesStorage object at 0x7fdc0b5b2730>.
argus-docker-api-1       |
argus-docker-api-1       | The CSS file 'rest_framework/css/bootstrap.min.css' references a file which could not be found:
argus-docker-api-1       |   rest_framework/css/bootstrap.min.css.map
argus-docker-api-1       |
argus-docker-api-1       | Please check the URL references in this CSS file, particularly any
argus-docker-api-1       | relative paths which might be pointing to the wrong location.
argus-docker-api-1       |
argus-docker-api-1       | [INFO  tini (1)] Spawned child process '/bin/sh' with pid '6'
argus-docker-api-1       | [INFO  tini (1)] Main child exited normally (with status '1')
argus-docker-api-1 exited with code 1
```

**Comment by lunkwill42** [comment]
This was finished and published a while ago, as this repository proves. Closing this. Other issues can be opened for updates and fixes.
