### ISSUE TITLE
Make a workflow that builds automated PRs when new back-end or front-end is released

### ISSUE THREAD

**Issue by lunkwill42** [Uninett/argus-docker#4]
We should add a workflow to this repository that, when triggered by a new GitHub release of either the back-end or front-end will update the `docker-compose.yml` file with the new versions and post an automated PR to be reviewed.

Potential tasks:

- [ ] Figure out how a GitHub release in one repo can be set to trigger a workflow in another
- [ ] Figure out how a workflow in this repo can be triggered and receive information about which component triggered it (backend or frontend) and what the new version number is
- [ ] Figure out if/how a GitHub Actions workflow can post an automated PR

**Comment by johannaengland** [comment]
Potential helpful links to solve this issue: 
- [create a GitHub app that responds to webhook events](https://docs.github.com/en/apps/creating-github-apps/writing-code-for-a-github-app/building-a-github-app-that-responds-to-webhook-events)
